# Generated by Django 3.2.18 on 2023-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailoring', '0002_auto_20230223_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
